import { useEffect, useState } from 'react'
import './App.css'

type Value = { id: string; name: string; behavior: string; concern: string }
type Stage = { id: string; name: string; owner: string; method: string; purpose: string; advance: string }
type Competency = { id: string; name: string; source: string; evidence: string; stageId: string; included: boolean }
type Item = { id: string; competencyId: string; question: string; probe: string; low: string; meets: string; high: string }
type Draft = { company: string; culture: string; values: Value[]; role: string; description: string; outcomes: string; requirements: string; teachable: string; challenges: string; stages: Stage[]; competencies: Competency[]; items: Item[]; approved: boolean }
const uid = () => crypto.randomUUID()
const empty = (): Draft => ({ company: '', culture: '', values: [], role: '', description: '', outcomes: '', requirements: '', teachable: '', challenges: '', stages: [], competencies: [], items: [], approved: false })
const pages = ['Welcome', 'Company', 'Role', 'Hiring steps', 'Competencies', 'Interview kit']
const patterns = [
  [/quality|accuracy|detail|inspect|registration|proof/i, 'Quality and attention to detail', 'Checks work against an agreed standard and catches errors early.'],
  [/troubleshoot|problem|repair|equipment|press|machine/i, 'Problem solving', 'Investigates what changed, tests possible causes, and knows when to ask for help.'],
  [/deadline|schedule|production|prioriti|pace/i, 'Planning and delivery', 'Organizes work, communicates delays, and protects quality under time pressure.'],
  [/team|collaborat|communicat|customer|lead/i, 'Communication and teamwork', 'Shares useful information and helps the next person complete their work.'],
  [/learn|train|software|system|adapt/i, 'Learning and adaptability', 'Learns a process, applies feedback, and explains what changed.'],
  [/safe|safety|clean|housekeep/i, 'Safe work practices', 'Follows the relevant safety process and keeps the work area ready for use.'],
] as const

function App() {
  const [d, setD] = useState<Draft>(() => { try { return { ...empty(), ...JSON.parse(localStorage.getItem('efactor-draft') || '{}') } } catch { return empty() } })
  const [page, setPage] = useState(0)
  const [message, setMessage] = useState('')
  useEffect(() => { localStorage.setItem('efactor-draft', JSON.stringify(d)) }, [d])
  const change = (patch: Partial<Draft>) => setD(old => ({ ...old, ...patch, items: patch.items ?? [], approved: false }))
  const editValue = (id: string, patch: Partial<Value>) => change({ values: d.values.map(v => v.id === id ? { ...v, ...patch } : v) })
  const editStage = (id: string, patch: Partial<Stage>) => change({ stages: d.stages.map(s => s.id === id ? { ...s, ...patch } : s) })
  const editComp = (id: string, patch: Partial<Competency>) => change({ competencies: d.competencies.map(c => c.id === id ? { ...c, ...patch } : c) })
  const editItem = (id: string, patch: Partial<Item>) => change({ items: d.items.map(q => q.id === id ? { ...q, ...patch } : q) })
  const propose = () => {
    const source = [d.description, d.outcomes, d.requirements, d.challenges].join(' ')
    const role = patterns.filter(([re]) => re.test(source)).map(([, name, evidence]) => ({ id: uid(), name, evidence, source: 'Role description', stageId: '', included: true }))
    const values = d.values.filter(v => v.name.trim()).map(v => ({ id: uid(), name: v.name, evidence: v.behavior, source: 'Company value', stageId: '', included: true }))
    change({ competencies: [...role, ...values], items: [] })
    setMessage('Suggestions are ready. Review their evidence and assign each to a hiring step.')
  }
  const makeKit = () => {
    const selected = d.competencies.filter(c => c.included)
    if (!selected.length || selected.some(c => !c.stageId || !c.name.trim() || !c.evidence.trim()) || !d.stages.length) { setMessage('Include at least one complete competency and assign every included competency to a step.'); return }
    const prior = new Map(d.items.map(item => [item.competencyId, item]))
    change({ items: selected.map(c => prior.get(c.id) || {
      id: uid(), competencyId: c.id,
      question: /work|sample|practical|task/i.test(d.stages.find(s => s.id === c.stageId)?.method || '') ? `Show how you would demonstrate ${c.name.toLowerCase()} in this task. What did you notice and do?` : `Tell me about a specific time you demonstrated ${c.name.toLowerCase()} at work. What happened, what did you do, and what was the result?`,
      probe: 'What was your own part? What did you notice? What would you do differently?',
      low: `Little relevant evidence, or actions worked against this behavior: ${c.evidence}`,
      meets: `A specific example shows this behavior: ${c.evidence}`,
      high: `A detailed example shows this behavior independently and explains its effect: ${c.evidence}`,
    }) })
    setPage(5); setMessage('Draft generated. Review and edit the questions and anchors before approval.')
  }
  const example = () => {
    setD({ company: 'Example organization', culture: 'A small production team that checks work carefully and communicates problems early.', values: [{ id: uid(), name: 'Responsibility', behavior: 'Names a problem, takes an appropriate next step, and keeps affected teammates informed.', concern: 'Hides a quality issue or shifts blame.' }], role: 'Screen Printing Specialist', description: 'Prepare and run print jobs. Check color, placement, and registration against an approved sample. Use equipment safely and work with the team to meet deadlines.', outcomes: 'Produce accurate work and catch print issues before a run continues.', requirements: 'Attention to detail and ability to follow a production process.', teachable: 'Specific equipment and scheduling software.', challenges: 'A print drifts from the approved sample during a production run.', stages: [{ id: uid(), name: 'Initial interview', owner: 'Hiring manager', method: 'Conversation', purpose: 'Explore past work and quality concerns.', advance: 'Review the evidence against each criterion.' }, { id: uid(), name: 'Work sample', owner: 'Production lead', method: 'Practical task', purpose: 'Observe a representative quality check.', advance: 'Review observed work against scoring anchors.' }], competencies: [], items: [], approved: false })
    setPage(1); setMessage('Anonymous example loaded. Its steps are illustrative and editable.')
  }
  const field = (label: string, key: keyof Pick<Draft, 'company'|'culture'|'role'|'description'|'outcomes'|'requirements'|'teachable'|'challenges'>, multi = false, hint = '') => <label>{label}{multi ? <textarea value={d[key]} placeholder={hint} onChange={e => change({ [key]: e.target.value })} /> : <input value={d[key]} placeholder={hint} onChange={e => change({ [key]: e.target.value })} />}</label>
  return <div className="app"><aside className="side"><div className="brand"><span className="brand-mark">EF</span><span>E FACTOR <small>LEADERSHIP</small></span></div><p className="side-label">INTERVIEW SYSTEM</p><nav>{pages.map((name, i) => <button key={name} className={page === i ? 'current' : ''} onClick={() => { setPage(i); setMessage('') }}><span>{i ? String(i).padStart(2, '0') : '⌂'}</span>{name}</button>)}</nav><div className="side-foot">● &nbsp; Draft saved in this browser<small>Prototype workspace</small></div></aside><div className="workspace"><header><span>INTERVIEW DESIGN STUDIO</span><span>{d.company || 'New company'} &nbsp; <b>EF</b></span></header><div className="prototype-banner">Prototype: setup is stored only in this browser. Use sample company details and no real candidate information.</div><main><div className="eyebrow">{page ? `SETUP / ${String(page).padStart(2, '0')} OF 05` : 'A BETTER WAY TO INTERVIEW'}</div>
    {page === 0 && <><h1>Build interviews around<br/><em>what matters.</em></h1><p className="lead">Turn company values, the work of a real role, and your own hiring process into useful questions and consistent scoring guidance.</p><div className="actions"><button className="primary" onClick={() => setPage(1)}>Start an interview kit →</button><button className="link" onClick={example}>Explore an anonymous example</button></div><div className="overview">{[['01','Describe the company','Define values through behavior people can observe.'],['02','Define the role','Review proposed competencies drawn from the work.'],['03','Shape the process','Add hiring steps, then approve the interview kit.']].map(x => <div key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></>}
    {page === 1 && <><h1>Start with the <em>company.</em></h1><p className="lead">Describe how people work here. Give examples that a manager could observe.</p><section className="card">{field('Company name','company')}{field('What is the work environment like?','culture',true,'Describe the team and how people work together.')}</section><div className="section-head"><div><h2>Values in action</h2><p>Give each value a behavior and an example of concern.</p></div><button className="secondary" onClick={() => change({ values: [...d.values, { id: uid(), name: '', behavior: '', concern: '' }] })}>+ Add value</button></div>{d.values.map((v,i) => <section className="card" key={v.id}><div className="card-head"><h3>Value {i+1}</h3><button className="link" onClick={() => change({ values: d.values.filter(x => x.id !== v.id) })}>Remove</button></div><label>Value name<input value={v.name} onChange={e => editValue(v.id,{name:e.target.value})}/></label><label>What would a manager see someone do?<textarea value={v.behavior} onChange={e => editValue(v.id,{behavior:e.target.value})}/></label><label>What behavior would concern you?<textarea value={v.concern} onChange={e => editValue(v.id,{concern:e.target.value})}/></label></section>)}</>}
    {page === 2 && <><h1>Define the <em>role.</em></h1><p className="lead">Paste the job description, then add what success and challenge look like in practice.</p><section className="card">{field('Role title','role',false,'e.g. Screen Printing Specialist')}{field('Job description','description',true,'Paste the role duties and requirements here.')}<div className="columns">{field('What should this person do well in the first few months?','outcomes',true)}{field('What challenges arise in this work?','challenges',true)}{field('What must they bring on day one?','requirements',true)}{field('What can you teach?','teachable',true)}</div></section></>}
    {page === 3 && <><h1>Your process, <em>your way.</em></h1><p className="lead">Add the hiring steps your company uses. Each step can assess different evidence.</p><div className="section-head"><div><h2>Hiring steps</h2><p>Drag is not needed. Use the arrows to set the order.</p></div><button className="secondary" onClick={() => change({ stages: [...d.stages,{id:uid(),name:'',owner:'',method:'',purpose:'',advance:''}] })}>+ Add step</button></div>{!d.stages.length && <div className="empty">Add the first point where you assess a candidate.</div>}{d.stages.map((s,i) => <section className="card" key={s.id}><div className="card-head"><h3>{i+1}. {s.name || 'New hiring step'}</h3><div><button className="link" disabled={!i} onClick={() => { const a=[...d.stages]; [a[i-1],a[i]]=[a[i],a[i-1]]; change({stages:a}) }}>↑</button><button className="link" disabled={i===d.stages.length-1} onClick={() => { const a=[...d.stages]; [a[i+1],a[i]]=[a[i],a[i+1]]; change({stages:a}) }}>↓</button><button className="link" onClick={() => change({ stages:d.stages.filter(x=>x.id!==s.id), competencies:d.competencies.map(c=>c.stageId===s.id?{...c,stageId:''}:c) })}>Remove</button></div></div><div className="columns"><label>Step name<input value={s.name} onChange={e=>editStage(s.id,{name:e.target.value})}/></label><label>Who conducts it?<input value={s.owner} onChange={e=>editStage(s.id,{owner:e.target.value})}/></label><label>How does it work?<input value={s.method} placeholder="Conversation, tour, practical task..." onChange={e=>editStage(s.id,{method:e.target.value})}/></label><label>What must you learn?<textarea value={s.purpose} onChange={e=>editStage(s.id,{purpose:e.target.value})}/></label></div><label>What is needed to move forward?<textarea value={s.advance} onChange={e=>editStage(s.id,{advance:e.target.value})}/></label></section>)}</>}
    {page === 4 && <><h1>Choose what to <em>assess.</em></h1><p className="lead">Suggestions come from the role and values. Review the source, describe observable evidence, and assign each competency to a step.</p><div className="actions"><button className="secondary" onClick={propose}>Suggest from role and values</button><button className="link" onClick={() => change({ competencies:[...d.competencies,{id:uid(),name:'',source:'Added by company',evidence:'',stageId:'',included:true}] })}>+ Add your own</button></div>{!d.competencies.length && <div className="empty">No competencies yet. Generate suggestions, then edit them to match the role.</div>}{d.competencies.map(c => <section className="card competency" key={c.id}><div className="card-head"><label className="check"><input type="checkbox" checked={c.included} onChange={e=>editComp(c.id,{included:e.target.checked})}/> Include</label><span className="tag">{c.source}</span><button className="link" onClick={() => change({competencies:d.competencies.filter(x=>x.id!==c.id)})}>Remove</button></div><label>Competency<input value={c.name} onChange={e=>editComp(c.id,{name:e.target.value})}/></label><label>What would demonstrate it?<textarea value={c.evidence} onChange={e=>editComp(c.id,{evidence:e.target.value})}/></label><label>Assess at this step<select value={c.stageId} onChange={e=>editComp(c.id,{stageId:e.target.value})}><option value="">Choose a step</option>{d.stages.map(s=><option key={s.id} value={s.id}>{s.name || 'Untitled step'}</option>)}</select></label></section>)}{d.competencies.some(c=>c.source==='Company value') && <div className="hint">Review overlap between a role competency and a value. Count the same behavior twice only if you intend to.</div>}</>}
    {page === 5 && <><h1>Review the <em>interview kit.</em></h1><p className="lead">Edit every question and scoring anchor before managers use it. Changes return the kit to draft. Evidence notes and scores on this screen are for printing; they are not saved.</p><div className="actions no-print"><button className="secondary" onClick={makeKit}>Generate or refresh draft</button><button className="secondary" disabled={!d.items.length} onClick={()=>window.print()}>Print / save PDF</button><button className="primary" disabled={!d.items.length} onClick={()=>{setD(old=>({...old,approved:true}));setMessage('Kit approved in this browser prototype.')}}>Approve kit</button><span className={'badge '+(d.approved?'approved':'')}>{d.approved?'Approved':'Draft'}</span></div>{!d.items.length && <div className="empty">Assign competencies to steps, then generate the kit.</div>}{!!d.items.length && <section className="guide"><div className="eyebrow">MANAGER GUIDE</div><h2>Use the kit consistently</h2><p>Ask the approved core questions. Use follow-ups to clarify what the candidate personally did. Record examples beside each score, then score before discussing candidates with others. Mark missing evidence instead of guessing.</p><p><strong>Scale:</strong> 1 = below the described behavior · 2 = between 1 and 3 · 3 = meets it · 4 = between 3 and 5 · 5 = exceeds it.</p></section>}{d.stages.map((s,i)=>{const items=d.items.filter(q=>d.competencies.find(c=>c.id===q.competencyId)?.stageId===s.id);return items.length?<section className="kit-stage" key={s.id}><div className="stage-title"><div className="eyebrow">STEP {String(i+1).padStart(2,'0')}</div><h2>{s.name}</h2><p>{s.owner} · {s.method}</p><p>{s.purpose}</p></div>{items.map(q=>{const c=d.competencies.find(x=>x.id===q.competencyId)!;return <article className="card" key={q.id}><div className="card-head"><span className="tag">{c.name}</span><small>{c.source}</small></div><label>Question or task<textarea value={q.question} onChange={e=>editItem(q.id,{question:e.target.value})}/></label><label>Follow-up prompts<input value={q.probe} onChange={e=>editItem(q.id,{probe:e.target.value})}/></label><div className="anchors">{([['1','low'],['3','meets'],['5','high']] as const).map(([n,key])=><label key={n}><b>{n}</b><textarea value={q[key]} onChange={e=>editItem(q.id,{[key]:e.target.value})}/></label>)}</div><div className="score"><label>Evidence notes<textarea placeholder="What did the candidate say or do?"/></label><label>Score<select defaultValue=""><option value="">Not scored</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label></div></article>})}<p className="decision"><strong>Decision point:</strong> {s.advance || 'Not yet defined.'}</p></section>:null})}</>}
    {message && <div className="toast" role="status">{message}<button onClick={()=>setMessage('')}>×</button></div>}{page>0&&page<5&&<div className="bottom"><button className="link" onClick={()=>setPage(page-1)}>← Back</button><button className="primary" onClick={()=>setPage(page+1)}>Continue →</button></div>}
  </main></div></div>
}
export default App
