export type BankEntry = { id: string; category: string; name: string; evidence: string; signals: string[] }

// Original, editable prompts. These are not copied O*NET definitions or validated scales.
// Keep starter IDs stable so browser drafts can retain their bank selections.
const starter: BankEntry[] = [
  { id: 'judgment', category: 'Thinking and decisions', name: 'Judgment and decision making', evidence: 'Gathers relevant facts, weighs options against agreed criteria, and explains a reasoned next step.', signals: ['judgment', 'decision making', 'make decisions', 'assess options'] },
  { id: 'fact-finding', category: 'Thinking and decisions', name: 'Fact finding', evidence: 'Asks open questions, separates observations from assumptions, and checks gaps before reaching a conclusion.', signals: ['fact finding', 'investigation', 'investigate', 'research findings'] },
  { id: 'discretion', category: 'Safety and stewardship', name: 'Confidentiality and discretion', evidence: 'Handles sensitive information carefully and shares it only with people who need it for the work.', signals: ['confidential', 'sensitive information', 'privacy', 'discretion'] },
  { id: 'policy', category: 'Safety and stewardship', name: 'Policy application', evidence: 'Checks the applicable policy, recognizes when it does not answer the situation, and seeks review when needed.', signals: ['policy', 'policies', 'procedures', 'compliance'] },
  { id: 'communication', category: 'Communication', name: 'Clear communication', evidence: 'Explains the relevant facts and next steps in language the other person can use.', signals: ['communicate', 'communication', 'explain', 'present information'] },
  { id: 'collaboration', category: 'Working with others', name: 'Collaboration', evidence: 'Shares useful information, invites relevant input, and follows through on shared work.', signals: ['collaborate', 'collaboration', 'cross-functional', 'teamwork'] },
  { id: 'manager-partnership', category: 'Working with others', name: 'Manager partnership', evidence: 'Helps a manager understand options and take responsibility for an appropriate next step.', signals: ['partner with managers', 'advise managers', 'manager support', 'coach managers'] },
  { id: 'coaching', category: 'Leadership', name: 'Coaching and feedback', evidence: 'Gives specific feedback, listens to the response, and agrees on a practical next step.', signals: ['coach', 'coaching', 'feedback', 'develop staff'] },
  { id: 'prioritization', category: 'Planning and execution', name: 'Prioritization', evidence: 'Identifies what needs attention first, explains tradeoffs, and adjusts the plan when conditions change.', signals: ['prioritize', 'prioritization', 'competing priorities', 'multiple deadlines'] },
  { id: 'documentation', category: 'Communication', name: 'Documentation and follow-through', evidence: 'Records relevant facts accurately and closes the loop with the right people.', signals: ['document', 'recordkeeping', 'maintain records', 'follow through'] },
  { id: 'quality', category: 'Quality and reliability', name: 'Quality focus', evidence: 'Checks work against a clear standard, catches errors, and corrects them before they spread.', signals: ['quality', 'inspect', 'quality standards', 'accuracy', 'proof'] },
  { id: 'improvement', category: 'Planning and execution', name: 'Process improvement', evidence: 'Notices a recurring problem, tests a practical change, and checks whether it helped.', signals: ['process improvement', 'improve processes', 'workflow improvement', 'streamline'] },
]

type Row = [category: string, name: string, evidence: string, signals: string[]]
const additional: Row[] = [
  ['Communication', 'Active listening', 'Summarizes what was heard and checks understanding before responding.', ['active listening', 'listen to', 'understand concerns']],
  ['Communication', 'Clear verbal communication', 'Explains a point plainly and checks that the audience understands.', ['verbal communication', 'communicate verbally', 'present verbally']],
  ['Communication', 'Written communication', 'Writes accurate messages that state the action and audience clearly.', ['written communication', 'write reports', 'draft communications', 'correspondence']],
  ['Communication', 'Asking clarifying questions', 'Seeks missing details before acting on an unclear request.', ['clarifying questions', 'ask questions', 'gather requirements']],
  ['Communication', 'Explaining technical information', 'Translates a technical requirement into useful next steps.', ['explain technical', 'technical information', 'train users']],
  ['Communication', 'Giving and receiving feedback', 'Offers specific observations and uses feedback to adjust work.', ['give feedback', 'receive feedback', 'performance feedback']],
  ['Communication', 'Documentation', 'Records relevant facts clearly enough for another person to act.', ['documentation', 'document findings', 'written records']],
  ['Working with others', 'Customer service', 'Responds to a need, confirms the resolution, and follows up.', ['customer service', 'serve customers', 'customer support']],
  ['Working with others', 'Relationship building', 'Builds trust through reliable contact and useful follow-through.', ['build relationships', 'relationships', 'rapport']],
  ['Working with others', 'Conflict resolution', 'Clarifies differing views and helps people agree on a workable next step.', ['resolve conflict', 'conflict resolution', 'mediate disputes', 'employee relations']],
  ['Working with others', 'Coaching', 'Uses questions and specific examples to help another person improve.', ['coaching', 'coach employees', 'mentor']],
  ['Working with others', 'Knowledge sharing', 'Passes along useful methods and checks that others can apply them.', ['knowledge sharing', 'share knowledge', 'train colleagues']],
  ['Working with others', 'Coordinating handoffs', 'Communicates status, risks, and ownership at a transfer point.', ['handoff', 'coordinate shifts', 'transfer work']],
  ['Working with others', 'Working across teams', 'Coordinates work with people outside the immediate team.', ['cross-functional', 'across teams', 'interdepartmental']],
  ['Thinking and decisions', 'Problem identification', 'Names the problem and separates symptoms from the underlying issue.', ['identify problems', 'problem identification', 'diagnose issues']],
  ['Thinking and decisions', 'Root cause analysis', 'Tests likely causes against facts before selecting a fix.', ['root cause', 'analyze causes', 'investigate failures']],
  ['Thinking and decisions', 'Critical thinking', 'Checks assumptions and uses evidence to reach a conclusion.', ['critical thinking', 'analyze information', 'evaluate evidence']],
  ['Thinking and decisions', 'Practical judgment', 'Chooses a proportionate action within the role and knows when to escalate.', ['judgment', 'sound decisions', 'discretion']],
  ['Thinking and decisions', 'Decision making', 'Compares options against the job requirements and explains the choice.', ['decision making', 'make decisions', 'choose solutions']],
  ['Thinking and decisions', 'Evaluating tradeoffs', 'Explains what is gained and lost across possible actions.', ['tradeoffs', 'balance priorities', 'weigh options']],
  ['Thinking and decisions', 'Learning from mistakes', 'Acknowledges an error, corrects it, and changes the next attempt.', ['learn from mistakes', 'correct errors', 'lessons learned']],
  ['Thinking and decisions', 'Creative problem solving', 'Develops and tests a workable response when the usual method fails.', ['creative problem solving', 'innovative solutions', 'new solutions']],
  ['Planning and execution', 'Time management', 'Plans work realistically and adjusts when time becomes constrained.', ['time management', 'manage time', 'schedule workload']],
  ['Planning and execution', 'Organizing work', 'Sets a clear sequence, owners, and materials for the work.', ['organize work', 'coordinate tasks', 'plan workflow']],
  ['Planning and execution', 'Follow through', 'Completes commitments and updates the people waiting on them.', ['follow through', 'follow-up', 'close the loop']],
  ['Planning and execution', 'Meeting deadlines', 'Tracks due dates and raises a delay early enough to respond.', ['deadlines', 'on time', 'timely completion']],
  ['Planning and execution', 'Managing competing demands', 'Reassesses priorities and communicates tradeoffs as requests change.', ['competing demands', 'multiple priorities', 'high volume']],
  ['Planning and execution', 'Resource coordination', 'Matches people, materials, and time to the planned work.', ['allocate resources', 'coordinate resources', 'staffing schedules']],
  ['Quality and reliability', 'Attention to detail', 'Notices deviations from specifications before work moves forward.', ['attention to detail', 'detail oriented', 'verify details', 'registration']],
  ['Quality and reliability', 'Quality control', 'Checks output against a known standard and addresses a failed check.', ['quality control', 'quality assurance', 'inspection']],
  ['Quality and reliability', 'Accuracy', 'Verifies important information or measurements before relying on them.', ['accuracy', 'accurate records', 'precise measurements']],
  ['Quality and reliability', 'Checking work', 'Reviews work at defined points and corrects errors found.', ['check work', 'review work', 'proofread']],
  ['Quality and reliability', 'Consistency', 'Uses the same standard across repeated tasks and records exceptions.', ['consistent results', 'repeatable', 'standardized work']],
  ['Quality and reliability', 'Following procedures', 'Follows the approved process and flags a step that does not fit.', ['follow procedures', 'standard operating procedures', 'SOP']],
  ['Quality and reliability', 'Ownership', 'Takes responsibility for an outcome and addresses an issue promptly.', ['ownership', 'accountability', 'own outcomes']],
  ['Quality and reliability', 'Dependability', 'Meets commitments and tells others early when a plan needs to change.', ['dependable', 'reliable', 'attendance']],
  ['Learning and change', 'Learning new processes', 'Learns a new workflow and applies it correctly after practice.', ['learn new processes', 'learn systems', 'training']],
  ['Learning and change', 'Applying feedback', 'Makes a specific change after feedback and checks the result.', ['apply feedback', 'incorporate feedback', 'learn from feedback']],
  ['Learning and change', 'Adaptability', 'Adjusts the approach when conditions change without losing the standard.', ['adaptability', 'adapt', 'changing priorities']],
  ['Learning and change', 'Initiative', 'Notices a useful next action and takes it within the role.', ['initiative', 'self starter', 'proactive']],
  ['Learning and change', 'Continuous improvement', 'Uses results and feedback to refine the way work is done.', ['continuous improvement', 'improve performance', 'kaizen']],
  ['Learning and change', 'Troubleshooting unfamiliar problems', 'Tests a new problem systematically and asks for help at the right point.', ['troubleshoot', 'diagnose unfamiliar', 'solve new problems']],
  ['Learning and change', 'Working with incomplete information', 'Identifies what is known, names uncertainty, and seeks what is missing.', ['incomplete information', 'ambiguity', 'uncertainty']],
  ['Safety and stewardship', 'Safety practices', 'Follows safety steps and stops or escalates unsafe work.', ['safety', 'safely', 'safe operation', 'PPE', 'OSHA']],
  ['Safety and stewardship', 'Identifying hazards', 'Spots a hazard and takes the appropriate reporting or control step.', ['hazards', 'risk assessment', 'unsafe conditions']],
  ['Safety and stewardship', 'Protecting equipment', 'Uses equipment properly and reports wear or damage.', ['protect equipment', 'equipment care', 'machine maintenance']],
  ['Safety and stewardship', 'Handling confidential information', 'Limits access to sensitive records and uses approved handling practices.', ['confidential', 'privacy', 'sensitive records', 'personnel files']],
  ['Safety and stewardship', 'Following applicable requirements', 'Checks the governing requirement and seeks review when uncertain.', ['regulatory requirements', 'compliance', 'labor law', 'legal requirements']],
  ['Safety and stewardship', 'Raising concerns promptly', 'Reports a material issue early with enough detail to act.', ['report concerns', 'escalate issues', 'raise concerns']],
  ['Customer and business', 'Understanding customer requirements', 'Confirms what the customer needs and checks the work against it.', ['customer requirements', 'client needs', 'customer specifications']],
  ['Customer and business', 'Managing expectations', 'States what can be done, when, and what may change.', ['manage expectations', 'set expectations', 'communicate timelines']],
  ['Customer and business', 'Service recovery', 'Acknowledges a service problem and follows through on a remedy.', ['service recovery', 'customer complaints', 'resolve complaints']],
  ['Customer and business', 'Cost awareness', 'Considers the cost of a choice without losing required quality.', ['cost awareness', 'budget', 'control costs']],
  ['Customer and business', 'Reducing waste', 'Notices avoidable waste and makes a practical reduction.', ['reduce waste', 'scrap', 'material waste']],
  ['Customer and business', 'Balancing speed and quality', 'Makes delivery tradeoffs visible and protects agreed standards.', ['speed and quality', 'production pace', 'turnaround time']],
  ['Leadership', 'Delegation', 'Assigns clear ownership, support, and a check-in point.', ['delegate', 'delegation', 'assign work']],
  ['Leadership', 'Setting expectations', 'Defines the result, standard, and timing before work begins.', ['set expectations', 'performance expectations', 'define goals']],
  ['Leadership', 'Coaching performance', 'Uses specific examples to help someone improve job performance.', ['coach performance', 'performance management', 'develop employees']],
  ['Leadership', 'Addressing problems early', 'Raises a concern promptly and agrees on a next step.', ['address performance', 'early intervention', 'resolve issues']],
  ['Leadership', 'Fair decision making', 'Applies consistent job-related criteria and documents a decision.', ['fair decisions', 'consistent decisions', 'equitable decisions']],
  ['Leadership', 'Developing others', 'Provides practice, feedback, and opportunities for growth.', ['develop others', 'employee development', 'train staff']],
  ['Leadership', 'Planning capacity', 'Anticipates workload and adjusts staffing or resources.', ['capacity planning', 'staffing levels', 'workforce planning']],
  ['Leadership', 'Leading change', 'Explains a change, listens to concerns, and supports adoption.', ['lead change', 'change management', 'implement change']],
  ['Production and technical work', 'Reading specifications', 'Identifies the key requirements in a work order or technical specification.', ['specifications', 'work orders', 'blueprints', 'print instructions']],
  ['Production and technical work', 'Equipment setup', 'Prepares equipment to the required settings and checks readiness.', ['equipment setup', 'set up machines', 'press setup']],
  ['Production and technical work', 'Equipment operation', 'Operates equipment to the defined standard and monitors the result.', ['operate equipment', 'operate machines', 'run press']],
  ['Production and technical work', 'Materials handling', 'Selects, moves, and stores materials according to the work and safety requirements.', ['materials handling', 'inventory handling', 'load materials']],
  ['Production and technical work', 'Measurement', 'Uses the appropriate measure and confirms readings before acting.', ['measure', 'measurement', 'calibrate']],
  ['Production and technical work', 'Process monitoring', 'Watches key process signals and responds to drift.', ['process monitoring', 'monitor production', 'track output']],
  ['Production and technical work', 'Troubleshooting equipment', 'Checks likely causes of equipment trouble and escalates when needed.', ['troubleshoot equipment', 'machine problems', 'equipment issues']],
  ['Production and technical work', 'Preventive maintenance', 'Performs scheduled checks and records an issue before failure.', ['preventive maintenance', 'routine maintenance', 'maintain equipment']],
  ['Production and technical work', 'Inspecting finished work', 'Compares finished output with the approved standard.', ['inspect finished', 'final inspection', 'approved sample']],
]

export const competencyBank: BankEntry[] = [
  ...starter,
  ...additional.map(([category, name, evidence, signals]) => ({
    id: 'bank-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
    category, name, evidence, signals,
  })),
]
